// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBefwScOHtWsrngQApHY4jSGy6fGzh_niA',
    appId: '1:646035201718:web:2ec1e544384d49ccb19017',
    messagingSenderId: '646035201718',
    projectId: 'st-credit-test',
    authDomain: 'st-credit-test.firebaseapp.com',
    storageBucket: 'st-credit-test.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjhtwtBXNvgOYNCN9Q5C8-b4s4Mtfj9SY',
    appId: '1:646035201718:android:c583e39b000bea8fb19017',
    messagingSenderId: '646035201718',
    projectId: 'st-credit-test',
    storageBucket: 'st-credit-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGxb5i53qpygu-U1j2G2l_pnFg3thU6CQ',
    appId: '1:646035201718:ios:cb8d538972daaec5b19017',
    messagingSenderId: '646035201718',
    projectId: 'st-credit-test',
    storageBucket: 'st-credit-test.appspot.com',
    iosClientId: '646035201718-14d98ejb7nofn3pnhaet99efhb8f5gc3.apps.googleusercontent.com',
    iosBundleId: 'com.example.stCredit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGxb5i53qpygu-U1j2G2l_pnFg3thU6CQ',
    appId: '1:646035201718:ios:cb8d538972daaec5b19017',
    messagingSenderId: '646035201718',
    projectId: 'st-credit-test',
    storageBucket: 'st-credit-test.appspot.com',
    iosClientId: '646035201718-14d98ejb7nofn3pnhaet99efhb8f5gc3.apps.googleusercontent.com',
    iosBundleId: 'com.example.stCredit',
  );
}
